name: Get-AppJWT
description: A GitHub Action that gets a JWT for a GitHub App
author: PSModule
branding:
  icon: upload-cloud
  color: white

inputs:
  ClientID:
    description: The Client ID of the GitHub App
    required: true
  PrivateKey:
    description: The Private Key of the GitHub App
    required: true

outputs:
  JWT:
    description: The JWT for the GitHub App
    value: ${{ steps.Get-AppJWT.outputs.JWT }}

runs:
  using: composite
  steps:
    - name: Get-AppJWT
      id: Get-AppJWT
      shell: pwsh
      env:
        GITHUB_ACTION_INPUT_ClientID: ${{ inputs.ClientID }}
        GITHUB_ACTION_INPUT_PrivateKey: ${{ inputs.PrivateKey }}
      run: |
        # Get-AppJWT
        . "${{ github.action_path }}\scripts\main.ps1" -Verbose
