name: Action-Test

run-name: "Action-Test - [${{ github.event.pull_request.title }} #${{ github.event.pull_request.number }}] by @${{ github.actor }}"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ActionTestBasic:
    name: Action-Test - [Basic]
    runs-on: ubuntu-latest
    steps:
      # Need to check out as part of the test, as its a local action
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Action-Test
        id: Action-Test
        uses: ./
        with:
          ClientID: ${{ secrets.TEST_CLIENT_ID }}
          PrivateKey: ${{ secrets.TEST_PRIVATE_KEY }}

      - name: Show result (print)
        shell: pwsh
        env:
          JWT: ${{ steps.Action-Test.outputs.JWT }}
        run: |
          # Print the Json Web Token (JWT) to the console
          Write-Host "JWT: $env:JWT"

      - name: Show result (Get app)
        shell: pwsh
        env:
          JWT: ${{ steps.Action-Test.outputs.JWT }}
        run: |
          # Access the GitHub /app endpoint using the JWT as bearer token
          Invoke-RestMethod -Uri "$env:GITHUB_API_URL/app" -Method Get -Headers @{
              Authorization = "Bearer $env:JWT"
          }
